version: '3'

services:
  yuque-sync:
    build: .
    container_name: yuque-sync
    restart: always
    volumes:
      - /yuque:/data
    environment:
      # 必须设置的环境变量（请替换为你的实际值）
      - YUQUE_TOKEN=your_yuque_token_here
      - YUQUE_SESSION=your_yuque_session_here
      
      # 可选的环境变量（已有默认值）
      - YUQUE_BASE_URL=https://www.yuque.com
      - SAVE_PATH=/data
      - MONITOR_INTERVAL_MINUTES=10
    networks:
      - yuque-network

networks:
  yuque-network:
    driver: bridge